### ISSUE TITLE
Unable to run apps. Can’t find ussd-renderer

### ISSUE THREAD

**Issue by Luminus** [mobmewireless/colloquy#1]
Here’s what I get when I run bundle exec ussd-renderer -s app

```
bundler: command not found: ussd-renderer
Install missing gem executables with `bundle install`
```

I’ve already run bundle install and installed all gems and dependencies.

I’ve cloned the repo and tried to run this inside the /colloquy folder as well as the /colloquy/examples folder to no avail.

I’m running ruby 2.2.3 using rbenv.

I’d appreciate all the help I can get.

Thanks.

**Comment by gokulnath** [comment]
I am sorry, I just noticed that the documentation is wrong. We will update that.

**Please use the below workflow for now**
The command line application is named colloquy, easiest way to make it work is to install the gem.
 
```gem install colloquy```

After that cd into the examples directory, open config/flows.yaml and comment out flows 'active_record' and 'hangman' (They are not working currently).

```colloquy . -s``` from examples directory should work now.

Let's keep the issue open until documentation is fixed.

**Comment by Luminus** [comment]
Hi @gokulnath,

Thanks for getting back to me on this.

I already installed the colloquy gem and I’ve followed the steps you laid out above. 

I was still having trouble, but I’ve resolved it, so I’m documenting it here in case someone else runs into the same issues.

Running ```colloquy . -s``` from the examples directory produces this.

```
$ colloquy . -s
#<Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/luminus/Desktop/USSD/colloquy/examples/log/renderer.log>
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/2.2.0/logger.rb:636:in `initialize'
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/2.2.0/logger.rb:636:in `open'
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/2.2.0/logger.rb:636:in `create_logfile'
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/2.2.0/logger.rb:630:in `rescue in open_logfile'
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/2.2.0/logger.rb:627:in `open_logfile'
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/2.2.0/logger.rb:584:in `initialize'
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/2.2.0/logger.rb:318:in `new'
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/2.2.0/logger.rb:318:in `initialize'
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.1.14/lib/active_support/logger.rb:45:in `initialize'
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/colloquy-1.0.1/lib/colloquy/renderer.rb:183:in `new'
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/colloquy-1.0.1/lib/colloquy/renderer.rb:183:in `initialize_logger'
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/colloquy-1.0.1/lib/colloquy/renderer.rb:125:in `configure'
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/colloquy-1.0.1/lib/colloquy/renderer.rb:22:in `prepare!'
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/colloquy-1.0.1/lib/colloquy/simulator.rb:6:in `initialize'
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/colloquy-1.0.1/lib/colloquy/runner.rb:80:in `new'
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/colloquy-1.0.1/lib/colloquy/runner.rb:80:in `run!'
/Users/luminus/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/colloquy-1.0.1/bin/colloquy:10:in `<top (required)>'
/Users/luminus/.rbenv/versions/2.2.3/bin/colloquy:23:in `load'
/Users/luminus/.rbenv/versions/2.2.3/bin/colloquy:23:in `<main>’
```

There’s no ```log``` directory in the ```examples``` directory, so creating the ```log``` directory and the ```renderer.log``` file fixed it.

Now I can run the examples.

**Comment by rockcoolsaint** [comment]
how do I get colloquy to work on my fresh ruby project? What extra folders/files do I have to create?

**Comment by rockcoolsaint** [comment]
Hi @Luminus, I have tried your idea of creating the log and renderer.log file but I get the following error

$ colloquy . -s
#<Errno::ENOENT: No such file or directory @ realpath_rec - /tmp>
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/colloquy-1.0.1/lib/colloquy
/renderer.rb:200:in `realpath'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/colloquy-1.0.1/lib/colloquy
/renderer.rb:200:in `realpath'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/colloquy-1.0.1/lib/colloquy
/renderer.rb:200:in `block in load_paths'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/colloquy-1.0.1/lib/colloquy
/renderer.rb:194:in `each'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/colloquy-1.0.1/lib/colloquy
/renderer.rb:194:in `load_paths'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/colloquy-1.0.1/lib/colloquy
/renderer.rb:127:in `configure'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/colloquy-1.0.1/lib/colloquy
/renderer.rb:22:in `prepare!'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/colloquy-1.0.1/lib/colloquy
/simulator.rb:6:in `initialize'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/colloquy-1.0.1/lib/colloquy
/runner.rb:80:in `new'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/colloquy-1.0.1/lib/colloquy
/runner.rb:80:in `run!'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/colloquy-1.0.1/bin/colloquy
:10:in `<top (required)>'
c:/RailsInstaller/Ruby2.1.0/bin/colloquy:22:in `load'
c:/RailsInstaller/Ruby2.1.0/bin/colloquy:22:in `<main>'

**Comment by vishnugopal** [comment]
I've fixed documentation and updated everything to run on the latest Ruby, in case anybody is still interested!
